### ISSUE TITLE
Release hi-file-parser-0.1.3.0 here and on Hackage

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/hi-file-parser#10]
@snoyberg or @borsboom, if I create a release of `hi-file-parser-0.1.3.0` here, would you upload it to Hackage?

Thanks to @hsyl20, it would support GHC 9.4.1 and it clears the CI (which I have moved to GitHub Actions).

**Comment by snoyberg** [comment]
@hsyl20 thanks for the contribution! And @mpilgrem huge thank you for stepping up for all the maintenance and development you're doing on these repos.

I'll be happy to make a release to Hackage. If you provide me with your Hackage username, I'd also be happy to add you to the maintainer team over there.

**Comment by mpilgrem** [comment]
@snoyberg, thank you. I am 'mpilgrem' on Hackage too.

**Comment by snoyberg** [comment]
Awesome, added!

**Comment by mpilgrem** [comment]
Uploaded to Hackage!
