### ISSUE TITLE
Supports GHC 9.4.5 and GHC 9.6.1?

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/hi-file-parser#12]
My experiments suggest that the `*.hi` file format may have changed after GHC 9.4.4. I will raise a pull request with those experiments. I am getting failures (not for GHC 9.4.4):
~~~text
  test\HiFileParserSpec.hs:58:5:
  1) HiFileParser, should successfully deserialize interface for, x64/ghc9045
       uncaught exception: ErrorCall
       Prelude.Enum.Bool.toEnum: bad argument

  test\HiFileParserSpec.hs:58:5:
  2) HiFileParser, should successfully deserialize interface for, x64/ghc9061
       uncaught exception: ErrorCall
       Prelude.Enum.Bool.toEnum: bad argument
~~~

**Comment by mpilgrem** [comment]
@hsyl20, may I call on your assistance with the above? It looks to me that the `*.hi` format has changed again, after GHC 9.4.4.

**Comment by hsyl20** [comment]
Indeed it changed again in https://gitlab.haskell.org/ghc/ghc/-/commit/b43896ead0f5b4927ba53daafa851c9ab05ca41e

#14 should fix it.
