### ISSUE TITLE
Supports GHC 9.4.1?

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/hi-file-parser#5]
The `master` branch of Stack builds with GHC 9.4.1, but using it I am getting messages like:

~~~
Warning: Failed to decode module interface: C:\Users\mikep\Documents\Code\GitHub\stack\.stack-work\dist\22605e11\build\Path\Extended.hi
         Decoding failure: not enough bytes
~~~

I am wondering if the file format has changed with GHC 9.4.1?

**Comment by hsyl20** [comment]
Indeed a field has been added in the header: https://gitlab.haskell.org/ghc/ghc/-/commit/25977ab542a30df4ae71d9699d015bcdd1ab7cfb#9f11c1c113f11a416be9e556904531050cbb5b2e_173_193

**Comment by hsyl20** [comment]
And another here: https://gitlab.haskell.org/ghc/ghc/-/commit/3d31f11e83a3d60d17459457e036ae387fc95323#887e29e8fb42c2e95ced4d97d29913d823a7d72f_167_172

**Comment by hsyl20** [comment]
The last one removed transitive dependencies from interface files. I wonder if Stack will have to adapt to this :/

**Comment by mpilgrem** [comment]
Architectural matters relating to Stack tend to be outside of my capabilities. @snoyberg, may I ask your advice: if transitive dependencies have been removed from GHC's interface files from GHC 9.4.1, do you think that is problematic for Stack?

**Comment by hsyl20** [comment]
PR in https://github.com/commercialhaskell/hi-file-parser/pull/7
